#!/usr/bin/env bash
set -e

python src/01_generate_historical_scope_emissions.py
python src/02_plot_total_emissions.py
python src/03_plot_emissions_by_scope_stacked.py
python src/04_plot_carbon_intensity.py
python src/05_plot_scope3_transport.py
python src/06_plot_emission_share_by_scope.py
python src/07_plot_scope_comparison.py
python src/08_plot_production_vs_co2_scatter.py
python src/09_plot_cumulative_emissions.py
python src/10_plot_indexed_growth.py
python src/12_scope3_loading_sensitivity.py
python src/13_scope3_distance_sensitivity.py
python src/14_scope2_grid_ef_sensitivity.py
python src/15_demand_projection_to_2050.py
python src/16_decarbonization_pathways.py
python src/17_future_scenarios.py
python src/18_medium_demand_projection_plot.py
python src/19_integrated_pathway_stacked.py
python src/20_optimistic_vs_realistic_pathway.py
python src/21_mitigation_analysis.py
python src/22_table_assumptions.py
python src/23_table_scenarios.py
python src/24_table_summary_key_years.py
python src/25_table_robustness.py
python src/26_monte_carlo_uncertainty.py
python src/27_lmdi_decomposition.py
